appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: 4BG+p/xSnZMDtK3BzlQcLT7VULoNadW0dqx2T0EB0v+SWNTQ+NrCJiNTK5qsXGoZ57reVb3l8hXRmi3t7QVQws3WTOzNLyezH5foYmM2LnL8gZHMtogoEHl0WtHbw6+JLyKhMq0fI+CO6OfM6/DQJuJ80j1mJRwNvpkA5zQmabXd18U4ThnsMfqqVEXmpzwQHP6JKqnjF3uw38SPZzZaAGy0PZh6XNNcbwhK7R7x3778DvQs+vwuME5JKhgK61YdNcqt7+pS/BSanUl5BScR0Xn9p7LSkfYgyPgiEQABBOu6+4jDFB1Y+DSAF5/PZgShNts6aPIv13fI4OhytYtOeZJz8GY1fH/bSgkdoM8VFq0kYYbXyLkEWZVX5JNsj9WHiyWZJnCjv9Qt0Sh6+OkFucikHKjvoVC6UOCFv3JHrpb2J/eGiKCmVXt5buWD5t8SN7B5yJYVUbrY+DRNYjrtSWzERfBg54GxawWWYxTEKiXa0bj4wRczzd2DoWuSH48aP8qJ6wg4mOj0hXH9o/wnpjQaji/bm9JDRY3mqZADO7oiDhGkXYK+ukQVhAZSwGCUzYy4JKxlc6TpQhhYjDv4CCLaA2b2HJfVE+P40sunRZ5bsvOFWdtgkjTSmpYm1AJg77HjzXd+Ents4LDW/sBD80QLV5KD9IG3QWv44Qu7Cyk=}
conda_forge_output_validation: false
