travis:
  secure:
    BINSTAR_TOKEN: bCNmla/0a+CqOIaZ0br9olnTZ6ga+RtgM6jmbL6eFRy4lCOJ1y+baun4l+Jm2P+mw4+0keLabSYhhmKgNmiIKKOkjPpXWBx+RPh+uvlThzXHBGHkpUm9D9xXH44O/wVVSMXvkW5rY8fEWU051BOrP0fJktOOEwfzRVaaqsumWFLVvMtSr/51/9Em+/a1UG+o8BjiAP0Hoe9LJcZBYTwsJZXKQVFDoErBym1q8OZmdHpMjdsNaHoqSMN1MVFBgFGVEHNuBqHWrYVc6drFPQYmq9Zc1F5+7bLqtXipzIPvKsyNEAEipfhdGnOdrHzdcfE2NTEoNWil7pvJdjO+Ekpouq4lFvpLxEzT0tAfh5ijgO4yfxGKZ/bY1dxJVs5IDf1cKv8VunCpaeBRoz2bA+Bw6/eIb5PoCQWRkK9UWyts+KLZpF7bYpCIx9Dj79wTJgtjrPY+l1Ba8CXsNAgfcYhgLnZMVe3KdUz8/a22/dTx2sMjNgvb5+77G3/h8jDmjupCcW0wKiAYrnIFK4p1Eitf+hhmHfWpEklYXs6oSQRPohX9Gb5jrJ9xp1TvG6DBlPaP/i4JQC+4zlwGNZ2CKylDzkt1GntIPp3Svs8m3yHMcRqvC+PJtq8gdE/WgHW/Ss1QDL/lA+JOQ3ICl7Q1fR2aYghd8syDlBZNowvPtNieawc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
